services:
  ssl-certbot:
    build: . ${DOCKER_IMG_ORG}/${DOCKER_IMG_NAME}:${DOCKER_IMG_TAG:-latest}
    image: ${DOCKER_IMG_ORG}/${DOCKER_IMG_NAME}:${DOCKER_IMG_TAG:-latest}
    volumes:
      - ssl_data:/app

volumes:
  ssl_data:
    driver: local